<!DOCTYPE html>
<html>
<head>
    <title>PDF Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #ffffff;
            padding: 40px;
            color: #333;
            border: 1px solid #ddd;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin: 0;
        }
        .header, .footer {
            text-align: center;
            margin-bottom: 20px;
        }
        .header img {
            width: 150px;
            height: auto;
        }
        .title {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
            font-size: 28px;
        }
        .subtitle {
            text-align: center;
            color: #555;
            margin-bottom: 40px;
            font-size: 22px;
        }
        h3 {
            color: #666;
            margin-top: 30px;
        }
        .invoice-details {
            margin-bottom: 20px;
        }
        .invoice-details strong {
            font-size: 18px;
        }
        .proposed-cost-table, .details-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            color: #333;
            font-weight: bold;
        }
        td {
            background-color: #fff;
            color: #333;
        }
        .total-row {
            font-weight: bold;
            background-color: #f9f9f9;
        }
        .total-amount {
            color: #d9534f;
        }
        .signature-section {
            margin-top: 40px;
        }
        .signature-section h3 {
            margin-bottom: 10px;
        }
        .signature-line {
            border-bottom: 1px solid #333;
            width: 200px;
            margin-bottom: 40px;
        }
        .address-section {
            margin-top: 5px;
        }
        .address-section h3 {
            margin-bottom: 5px;
        }
        .address-line {
            border-bottom: 1px solid #333;
            width: 100%;
            margin-bottom: 20px;
            margin-top: 20px;
        }
        .signatures {
            display: flex;
            justify-content: space-between;
            margin-top: 10px;
        }
        .signatures .signature {
            width: 45%;
            text-align: center;
        }
        .designer-id {
            margin-top: -20px;
        }
    </style>
</head>
<body>
    
    <div class="title">
        Invoice
    </div>
    
    <div class="subtitle">
        {{ $project->title }}
    </div>

    <div class="invoice-details">
        <h3>Client: <strong>{{ $clientName }}</strong></h3>
        <h3>Designer: <strong>{{ $designerName }}</strong></h3>
    </div>

    <table class="proposed-cost-table">
        <tr>
            <th>Proposed Cost</th>
            <th>Amount (RM)</th>
        </tr>
        <tr>
            <td>Proposed Cost</td>
            <td>{{ number_format($finance->cost_estimation, 2) }}</td>
        </tr>
    </table>

    <table class="details-table">
        <tr>
            <th>Category</th>
            <th>Amount (RM)</th>
        </tr>
        <tr>
            <td>Estimation Cost</td>
            <td>{{ number_format($finance->actual_cost, 2) }}</td>
        </tr>
        <tr>
            <td>Tax</td>
            <td>{{ number_format($finance->tax, 2) }}</td>
        </tr>
        <tr>
            <td>Additional Fees</td>
            <td>{{ number_format($finance->additional_fees, 2) }}</td>
        </tr>
        <tr class="total-row">
            <td>Total Cost</td>
            <td class="total-amount">{{ number_format($totalCost, 2) }}</td>
        </tr>
    </table>

    <div class="address-section">
        <h4>Client Address</h4>
        
        <div class="address-line"></div>     
    </div>
    <div class="signature-section signatures">
        <h4>Client Signature</h4>
        <div class="signature">          
            <div class="signature-line"></div>
        </div>
        <h4>Designer Signature</h4>
        <div class="signature">           
            <div class="signature-line"></div>
        </div>
    </div>
    
    <div class="footer">
        <p>Generated by MyReno</p>
    </div>
</body>
</html>
